import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const planPath = path.join(
  process.env.USERPROFILE || "",
  ".cursor",
  "plans",
  "bark_for_life_next.js_6388717b.plan.md",
);

const plan = fs.readFileSync(planPath, "utf8");
const line = plan.split(/\r?\n/).find((l) => l.startsWith("A C Paint — "));
if (!line) {
  console.error("Could not find tuber line in plan");
  process.exit(1);
}

const sep = " — ";
const parts = line.split("; ").map((p) => p.trim()).filter(Boolean);
const tubers = parts.map((p) => {
  const i = p.indexOf(sep);
  if (i === -1) throw new Error(`Missing separator in: ${p}`);
  return {
    name: p.slice(0, i).trim(),
    abbreviation: p.slice(i + sep.length).trim(),
  };
});

const out = `/** Auto-generated by scripts/gen-tubers.mjs — do not edit by hand */
export type Tuber = { name: string; abbreviation: string };

export const tubers: readonly Tuber[] = ${JSON.stringify(tubers, null, 2)} as const;

export const tuberCount = tubers.length;
`;

const target = path.join(root, "src", "data", "tubers.ts");
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out, "utf8");
console.log(`Wrote ${tubers.length} tubers to ${target}`);
