/** Auto-generated by scripts/gen-tubers.mjs — do not edit by hand */
export type Tuber = { name: string; abbreviation: string };

export const tubers: readonly Tuber[] = [
  {
    "name": "A C Paint",
    "abbreviation": "ACP"
  },
  {
    "name": "A la. Mode",
    "abbreviation": "ALM"
  },
  {
    "name": "Amber Queen",
    "abbreviation": "A Q"
  },
  {
    "name": "Apple Blossom",
    "abbreviation": "AB"
  },
  {
    "name": "B J Dusty Rose",
    "abbreviation": "BJ DR"
  },
  {
    "name": "Beep Beep",
    "abbreviation": "BB"
  },
  {
    "name": "Betty Ann",
    "abbreviation": "BA"
  },
  {
    "name": "Bloomquist Carol Ann",
    "abbreviation": "BQ CA"
  },
  {
    "name": "Bloomquist Larrie Ann",
    "abbreviation": "BQ LA"
  },
  {
    "name": "Black Satin",
    "abbreviation": "BS"
  },
  {
    "name": "Blizzard",
    "abbreviation": "Bliz"
  },
  {
    "name": "Boom Boom White",
    "abbreviation": "BBW"
  },
  {
    "name": "Bride to Be",
    "abbreviation": "BtB"
  },
  {
    "name": "Brown Sugar",
    "abbreviation": "Br S"
  },
  {
    "name": "Cafe au Lait",
    "abbreviation": "CAL"
  },
  {
    "name": "Carl Chilson",
    "abbreviation": "CC"
  },
  {
    "name": "Checkers",
    "abbreviation": "Ch"
  },
  {
    "name": "Chilson’s Pride",
    "abbreviation": "CP"
  },
  {
    "name": "Christopher Mingus",
    "abbreviation": "CM"
  },
  {
    "name": "Citron da Cap",
    "abbreviation": "CdC"
  },
  {
    "name": "Cornel Bronze",
    "abbreviation": "CB"
  },
  {
    "name": "Crazy Legs",
    "abbreviation": "CL"
  },
  {
    "name": "Cutie Patootie",
    "abbreviation": "CP"
  },
  {
    "name": "Dad’s Favorite",
    "abbreviation": "DF"
  },
  {
    "name": "Diva",
    "abbreviation": "Diva"
  },
  {
    "name": "Dot Com",
    "abbreviation": "DC"
  },
  {
    "name": "Fluffles",
    "abbreviation": "Fl"
  },
  {
    "name": "Frank Holmes",
    "abbreviation": "FH"
  },
  {
    "name": "Giggles",
    "abbreviation": "Gig"
  },
  {
    "name": "Gloriousa",
    "abbreviation": "Gl"
  },
  {
    "name": "Golden Sceptar",
    "abbreviation": "GS"
  },
  {
    "name": "Gonzo Grape",
    "abbreviation": "GG"
  },
  {
    "name": "Halloway Candy",
    "abbreviation": "HC"
  },
  {
    "name": "Hamari Gold",
    "abbreviation": "HG"
  },
  {
    "name": "Hollyhills Black Beauty",
    "abbreviation": "HH bl B"
  },
  {
    "name": "Heather Mingus",
    "abbreviation": "HM"
  },
  {
    "name": "Irish Ruffles",
    "abbreviation": "IR"
  },
  {
    "name": "Jessie G",
    "abbreviation": "JG"
  },
  {
    "name": "Joycie C",
    "abbreviation": "JC"
  },
  {
    "name": "Juanita",
    "abbreviation": "Juan"
  },
  {
    "name": "KA Keltie Rose",
    "abbreviation": "KR"
  },
  {
    "name": "Karris 150",
    "abbreviation": "K 150"
  },
  {
    "name": "Keigai Ann",
    "abbreviation": "KA"
  },
  {
    "name": "Koko Puff",
    "abbreviation": "KP"
  },
  {
    "name": "Lavendar Perfection",
    "abbreviation": "LP"
  },
  {
    "name": "Lemon Tart",
    "abbreviation": "LT"
  },
  {
    "name": "Lights Out",
    "abbreviation": "LO"
  },
  {
    "name": "Lovely Lana",
    "abbreviation": "LL"
  },
  {
    "name": "Maarn (Silvia)",
    "abbreviation": "M"
  },
  {
    "name": "Magic Moment",
    "abbreviation": "MM"
  },
  {
    "name": "Mai Tai",
    "abbreviation": "MT"
  },
  {
    "name": "Marie Elana",
    "abbreviation": "ME"
  },
  {
    "name": "Marmalade",
    "abbreviation": "Mar"
  },
  {
    "name": "Mikauyla Miranda",
    "abbreviation": "Mi Mi"
  },
  {
    "name": "Midnight Moon",
    "abbreviation": "Mid M"
  },
  {
    "name": "Mingus Harry",
    "abbreviation": "MH"
  },
  {
    "name": "Mingus Heather",
    "abbreviation": "MH"
  },
  {
    "name": "Mingus Tori",
    "abbreviation": "MT"
  },
  {
    "name": "Moonstruck",
    "abbreviation": "Moon"
  },
  {
    "name": "Mingus Phillip Sr",
    "abbreviation": "M PSr"
  },
  {
    "name": "Narrow’s Brett",
    "abbreviation": "NB"
  },
  {
    "name": "New Baby",
    "abbreviation": "NB"
  },
  {
    "name": "Pee Gee",
    "abbreviation": "PG"
  },
  {
    "name": "Peach Fuzz",
    "abbreviation": "PFuz"
  },
  {
    "name": "Phillip Mingus Sr",
    "abbreviation": "PMSr"
  },
  {
    "name": "Pinelands Prickles",
    "abbreviation": "PPr"
  },
  {
    "name": "Popcycle Toes",
    "abbreviation": "Ptoes"
  },
  {
    "name": "Polka",
    "abbreviation": "Pol"
  },
  {
    "name": "PuNkin Spice",
    "abbreviation": "PS"
  },
  {
    "name": "Rebecca Lynn",
    "abbreviation": "Rly"
  },
  {
    "name": "River’s Carol Ann",
    "abbreviation": "RCA"
  },
  {
    "name": "River’s Watermellon",
    "abbreviation": "RW"
  },
  {
    "name": "Robann Royal",
    "abbreviation": "RR"
  },
  {
    "name": "Rockstar",
    "abbreviation": "Rst"
  },
  {
    "name": "Rosemary Webb",
    "abbreviation": "RWeb"
  },
  {
    "name": "Sandia Brocade",
    "abbreviation": "SB"
  },
  {
    "name": "Show and Tell",
    "abbreviation": "SaT"
  },
  {
    "name": "Steven David",
    "abbreviation": "StD"
  },
  {
    "name": "Sugar Cane",
    "abbreviation": "SC"
  },
  {
    "name": "Sugar Lips",
    "abbreviation": "SL"
  },
  {
    "name": "Sweet Dreams",
    "abbreviation": "Sw D"
  },
  {
    "name": "Sweet Natalie",
    "abbreviation": "Sw N"
  },
  {
    "name": "Tanner Joe",
    "abbreviation": "TJ"
  },
  {
    "name": "Terra Cotta",
    "abbreviation": "TC"
  },
  {
    "name": "Tomo",
    "abbreviation": "Tomo"
  },
  {
    "name": "Touche",
    "abbreviation": "Tou"
  },
  {
    "name": "Valley Rust Bucket",
    "abbreviation": "VRB"
  },
  {
    "name": "Vixen",
    "abbreviation": "Vix"
  },
  {
    "name": "Wine Eyed Jill",
    "abbreviation": "WEJ"
  },
  {
    "name": "Wizard of Oz",
    "abbreviation": "W Oz"
  },
  {
    "name": "Woodland’s Merinda",
    "abbreviation": "WM"
  },
  {
    "name": "Wyn’s Mauve Mist",
    "abbreviation": "Wy M."
  }
] as const;

export const tuberCount = tubers.length;
